deptrac:
  ruleset:
    Layer:
      - Ast
      - Symfony
    Console:
      - Analyser
      - OutputFormatter
      - DependencyInjection
      - File
      - Time
      - Symfony
    Dependency:
      - Ast
    Analyser:
      - Layer
      - Dependency
      - Ast
      - Symfony
    OutputFormatter:
      - DependencyInjection
      - Symfony
    Ast:
      - File
      - InputCollector
      - Symfony
    InputCollector:
      - File
      - Symfony
    DependencyInjection:
      - Symfony
    Contract:
      - Symfony
    File:
      - Symfony